### PR TITLE
Add authentication through basic local strategy

### PR DESCRIPTION
**Pull request by romgar**
First step towards user account creation / authentication.
Not production ready at all, using local objects to define users with passwords (!).

### CODE REVIEW

**Comment by romgar** [comment]
TODO list:
- [x] Login with local strategy,
- [x] Logout with local strategy (implies session working),
- [ ] Update local strategy to use a db to save the user credentials,
- [ ] Create an account creation form.

**Comment by paoesco** [comment]
I've rebased from develop after the merge of PR #2 
CI Travis is added and working (develop had Travis).
I am now using bin/www for starting the project.

**Comment by paoesco** [comment]
Two comments :
- The view says using email but the login is done with username (little inconsistency)
- We should add bcrypt to hash password in database

**Comment by romgar** [comment]
@paoesco could you let me handle rebasing in the future please? I wanted to clean my commits before merging, and what you did doesn't really help me.

**Comment by paoesco** [comment]
Ok sorry

**Comment by romgar** [comment]
Let's keep the MR as small as possible, there is still a lot to do before being used, but I will create small MRs for each new piece.

**Pull request merged**
